name: Sudoless tcpdump

inputs:
  runsOn:
    description: 'OS (ubuntu-latest, macos-latest, windows-latest, ...)'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup sudoless tcpdump (linux only)
      if: ${{ success() && startsWith(inputs.runsOn, 'ubuntu-') }}
      shell: bash
      run: |
        sudo groupadd pcap
        sudo usermod -a -G pcap $USER
        sudo chgrp pcap /usr/bin/tcpdump
        sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/tcpdump

    - name: Setup sudoless tcpdump (macos only)
      if: ${{ success() && startsWith(inputs.runsOn, 'macos-') }}
      shell: bash
      run: |
        sudo chown $(whoami):admin /dev/bpf*
