name: Release

on:
  push:
    branches:
      - master

jobs:
  test-tsd:
    name: 'Test: TSD'
    uses: ./.github/workflows/test-tsd.yaml

  test-full:
    name: 'Tests: Unit (+coverage) & Integration'
    uses: ./.github/workflows/test-lts-matrix.yaml
    with:
      testUnit: test-with-coverage
      testIntegration: test
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'hertzg/node-net-keepalive' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    needs:
      - test-full
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/workflows/actions/setup
        with:
          nodeVersion: '*'

      - name: Upgrade npm to a version that supports OIDC trusted publishing
        run: npm install --global npm@latest

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
