name: 'test:tsd'

on:
  workflow_dispatch:
    inputs:
      runsOn:
        description: 'OS (ubuntu-latest, macos-latest, windows-latest, ...)'
        type: string
        default: ubuntu-latest
      nodeVersion:
        description: 'Node (* for latest or 20, 18, ...)'
        type: string
        default: '*'

  workflow_call:
    inputs:
      runsOn:
        type: string
        default: ubuntu-latest
      nodeVersion:
        type: string
        default: '*'

jobs:
  tsd:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/actions/setup
        with:
          nodeVersion: ${{ inputs.nodeVersion }}

      - run: npm run test:tsd
